# base node image
FROM node:22-alpine3.20 AS base

# Install all node_modules, including dev dependencies
FROM base AS deps
RUN mkdir /app && mkdir /app/prisma
WORKDIR /app

ADD package.json package-lock.json ./
ADD prisma/schema.prisma ./prisma/schema.prisma
# This installs the dependencies from package-lock.json
# (like npm install, but will fail if package.json and package-lock.json are out of sync)
RUN npm ci
RUN npx prisma generate

# Setup production node_modules
FROM base AS production-deps
RUN mkdir /app
WORKDIR /app

COPY --from=deps /app/node_modules /app/node_modules
ADD package.json package-lock.json ./
RUN npm prune --production

# Build the app
FROM base
ENV NODE_ENV=production
RUN mkdir /app
WORKDIR /app

COPY --from=deps /app/node_modules /app/node_modules
ADD common ./common
ADD market-crawler ./market-crawler
ADD data ./data
ADD package.json package-lock.json tsconfig.json ./
ADD .env.crawler ./.env

ENTRYPOINT ["npm", "run"]