#!/bin/sh

# Expected to be set externally

# GH_REPO=https://github.com/Taum/databases
# ORIGIN_BRANCH=master
# GH_TOKEN=github_pat_...


# Exit on error
set -e

# Check if gh CLI is installed
if ! command -v gh &> /dev/null; then
    echo "GitHub CLI (gh) is not installed. Please install it first."
    echo "Visit: https://cli.github.com/manual/installation"
    exit 1
fi

echo "$GH_TOKEN" > /tmp/gh_token
export GH_TOKEN=

gh config set prompt disabled

gh auth login --with-token < /tmp/gh_token

BRANCH_NAME="auto-update-$(date +%Y%m%d-%H%M%S)"

# Check if user is authenticated with GitHub
if ! gh auth status &> /dev/null; then
    echo "You are not authenticated with GitHub. Please run 'gh auth login' first."
    exit 1
fi

gh auth setup-git
git config --global user.email "automated@marketbot.dev"
git config --global user.name "Marketbot"

export COMMUNITY_DB_PATH=$(mktemp -d)

gh repo clone $GH_REPO $COMMUNITY_DB_PATH -- --bare

CURRENT_DIR=$(pwd)
cd $COMMUNITY_DB_PATH

git branch $BRANCH_NAME $ORIGIN_BRANCH
git symbolic-ref HEAD refs/heads/$BRANCH_NAME

cd $CURRENT_DIR

# Run the crawler
npm run crawler-all-uniques

cd $COMMUNITY_DB_PATH

git push -u origin $BRANCH_NAME

gh pr create --title "Marketbot: $BRANCH_NAME" --body "This PR was autoamtically generated by Marketbot" --base "$ORIGIN_BRANCH" --head "$BRANCH_NAME" -R "$GH_REPO"
